[buildPlans.pragmatasevka]
family = "Pragmatasevka"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true
hintParams = ["-a", "qqq"]

  [buildPlans.pragmatasevka.variants]
  inherits = "ss08"

  [buildPlans.pragmatasevka.ligations]
  inherits = "dlig"
    enables = [
        "eqslasheq",
        "kern-dotty",
        "kern-bars",
        "llggeq",
        "connected-underscore", 
        "connected-number-sign",
        "connected-hyphen"
    ]
    disables = ["slash-asterisk"]

    [buildPlans.pragmatasevka.weights.regular]
    shape = 445
    menu = 400
    css = 400

    [buildPlans.pragmatasevka.weights.bold]
    shape = 850
    menu = 700
    css = 700

    [buildPlans.pragmatasevka.widths.normal]
    shape = 480
    menu = 5
    css = "normal"

    [buildPlans.pragmatasevka.metric-override]
    leading = 1000
    xHeight = 550

    [buildPlans.pragmatasevka.slopes]
    upright = "default.upright"
    italic = "default.italic"
